// packages/excalidraw/components/main-menu/DefaultItems.tsx
import clsx from "clsx";

import { THEME } from "@excalidraw/common";

import type { Theme } from "@excalidraw/element/types";

import {
  actionClearCanvas,
  actionLoadScene,
  actionSaveToActiveFile,
  actionShortcuts,
  actionToggleArrowBinding,
  actionToggleGridMode,
  actionToggleMidpointSnapping,
  actionToggleObjectsSnapMode,
  actionToggleSearchMenu,
  actionToggleStats,
  actionToggleTheme,
  actionToggleZenMode,
} from "../../actions";
import { actionToggleViewMode } from "../../actions/actionToggleViewMode";
import { getShortcutFromShortcutName } from "../../actions/shortcuts";
import { trackEvent } from "../../analytics";
import { useUIAppState } from "../../context/ui-appState";
import { useSetAtom } from "../../editor-jotai";
import { useI18n } from "../../i18n";
import { activeConfirmDialogAtom } from "../ActiveConfirmDialog";
import {
  useExcalidrawSetAppState,
  useExcalidrawActionManager,
  useExcalidrawElements,
  useAppProps,
  useApp,
} from "../App";
import { openConfirmModal } from "../OverwriteConfirm/OverwriteConfirmState";
import Trans from "../Trans";
import DropdownMenuItem from "../dropdownMenu/DropdownMenuItem";
import DropdownMenuItemCheckbox from "../dropdownMenu/DropdownMenuItemCheckbox";
import DropdownMenuItemContentRadio from "../dropdownMenu/DropdownMenuItemContentRadio";
import DropdownMenuSub from "../dropdownMenu/DropdownMenuSub";
import { settingsIcon, emptyIcon } from "../icons";
import {
  boltIcon,
  DeviceDesktopIcon,
  ExportIcon,
  ExportImageIcon,
  HelpIcon,
  LoadIcon,
  MoonIcon,
  save,
  searchIcon,
  SunIcon,
  TrashIcon,
  usersIcon,
} from "../icons";

import "./DefaultItems.scss";

export const LoadScene = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const elements = useExcalidrawElements();

  if (!actionManager.isActionEnabled(actionLoadScene)) {
    return null;
  }

  const handleSelect = async () => {
    if (
      !elements.length ||
      (await openConfirmModal({
        title: t("overwriteConfirm.modal.loadFromFile.title"),
        actionLabel: t("overwriteConfirm.modal.loadFromFile.button"),
        color: "warning",
        description: (
          <Trans
            i18nKey="overwriteConfirm.modal.loadFromFile.description"
            bold={(text) => <strong>{text}</strong>}
            br={() => <br />}
          />
        ),
      }))
    ) {
      actionManager.executeAction(actionLoadScene);
    }
  };

  return (
    <DropdownMenuItem
      icon={LoadIcon}
      onSelect={handleSelect}
      data-testid="load-button"
      shortcut={getShortcutFromShortcutName("loadScene")}
      aria-label={t("buttons.load")}
    >
      {t("buttons.load")}
    </DropdownMenuItem>
  );
};
LoadScene.displayName = "LoadScene";

export const SaveToActiveFile = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();

  if (!actionManager.isActionEnabled(actionSaveToActiveFile)) {
    return null;
  }

  return (
    <DropdownMenuItem
      shortcut={getShortcutFromShortcutName("saveScene")}
      data-testid="save-button"
      onSelect={() => actionManager.executeAction(actionSaveToActiveFile)}
      icon={save}
      aria-label={`${t("buttons.save")}`}
    >{`${t("buttons.save")}`}</DropdownMenuItem>
  );
};
SaveToActiveFile.displayName = "SaveToActiveFile";

export const SaveAsImage = () => {
  const setAppState = useExcalidrawSetAppState();
  const { t } = useI18n();
  return (
    <DropdownMenuItem
      icon={ExportImageIcon}
      data-testid="image-export-button"
      onSelect={() => setAppState({ openDialog: { name: "imageExport" } })}
      shortcut={getShortcutFromShortcutName("imageExport")}
      aria-label={t("buttons.exportImage")}
    >
      {t("buttons.exportImage")}
    </DropdownMenuItem>
  );
};
SaveAsImage.displayName = "SaveAsImage";

export const CommandPalette = (opts?: { className?: string }) => {
  const setAppState = useExcalidrawSetAppState();
  const { t } = useI18n();

  return (
    <DropdownMenuItem
      icon={boltIcon}
      data-testid="command-palette-button"
      onSelect={() => {
        trackEvent("command_palette", "open", "menu");
        setAppState({ openDialog: { name: "commandPalette" } });
      }}
      shortcut={getShortcutFromShortcutName("commandPalette")}
      aria-label={t("commandPalette.title")}
      className={opts?.className}
    >
      {t("commandPalette.title")}
    </DropdownMenuItem>
  );
};
CommandPalette.displayName = "CommandPalette";

export const SearchMenu = (opts?: { className?: string }) => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();

  return (
    <DropdownMenuItem
      icon={searchIcon}
      data-testid="search-menu-button"
      onSelect={() => {
        actionManager.executeAction(actionToggleSearchMenu);
      }}
      shortcut={getShortcutFromShortcutName("searchMenu")}
      aria-label={t("search.title")}
      className={opts?.className}
    >
      {t("search.title")}
    </DropdownMenuItem>
  );
};
SearchMenu.displayName = "SearchMenu";

export const Help = () => {
  const { t } = useI18n();

  const actionManager = useExcalidrawActionManager();

  return (
    <DropdownMenuItem
      data-testid="help-menu-item"
      icon={HelpIcon}
      onSelect={() => actionManager.executeAction(actionShortcuts)}
      shortcut="?"
      aria-label={t("helpDialog.title")}
    >
      {t("helpDialog.title")}
    </DropdownMenuItem>
  );
};
Help.displayName = "Help";

export const ClearCanvas = () => {
  const { t } = useI18n();

  const setActiveConfirmDialog = useSetAtom(activeConfirmDialogAtom);
  const actionManager = useExcalidrawActionManager();

  if (!actionManager.isActionEnabled(actionClearCanvas)) {
    return null;
  }

  return (
    <DropdownMenuItem
      icon={TrashIcon}
      onSelect={() => setActiveConfirmDialog("clearCanvas")}
      data-testid="clear-canvas-button"
      aria-label={t("buttons.clearReset")}
    >
      {t("buttons.clearReset")}
    </DropdownMenuItem>
  );
};
ClearCanvas.displayName = "ClearCanvas";

export const ToggleTheme = (
  props:
    | {
        allowSystemTheme: true;
        /**
         * Controls the theme of this UI component only.
         * You should subscribe to `props.onThemeChange` and control the theme
         * upstream.
         */
        theme: Theme | "system";
      }
    | {
        allowSystemTheme: false;
      },
) => {
  const { t } = useI18n();
  const appState = useUIAppState();
  const actionManager = useExcalidrawActionManager();
  const shortcut = getShortcutFromShortcutName("toggleTheme");
  const appProps = useAppProps();

  if (!actionManager.isActionEnabled(actionToggleTheme)) {
    return null;
  }

  if (props?.allowSystemTheme) {
    return (
      <DropdownMenuItemContentRadio
        name="theme"
        value={props.theme}
        onChange={(value: Theme | "system") => {
          if (appProps.onThemeChange) {
            appProps.onThemeChange(value);
            return;
          }

          console.warn(
            "MainMenu.DefaultItems.ToggleTheme: `<Excalidraw/> props.onThemeChange` must be defined to use system theme selection.",
          );
        }}
        choices={[
          {
            value: THEME.LIGHT,
            label: SunIcon,
            ariaLabel: `${t("buttons.lightMode")} - ${shortcut}`,
          },
          {
            value: THEME.DARK,
            label: MoonIcon,
            ariaLabel: `${t("buttons.darkMode")} - ${shortcut}`,
          },
          {
            value: "system",
            label: DeviceDesktopIcon,
            ariaLabel: t("buttons.systemMode"),
          },
        ]}
      >
        {t("labels.theme")}
      </DropdownMenuItemContentRadio>
    );
  }

  return (
    <DropdownMenuItem
      onSelect={(event) => {
        // do not close the menu when changing theme
        event.preventDefault();

        actionManager.executeAction(actionToggleTheme);
      }}
      icon={appState.theme === THEME.DARK ? SunIcon : MoonIcon}
      data-testid="toggle-dark-mode"
      shortcut={shortcut}
      aria-label={
        appState.theme === THEME.DARK
          ? t("buttons.lightMode")
          : t("buttons.darkMode")
      }
    >
      {appState.theme === THEME.DARK
        ? t("buttons.lightMode")
        : t("buttons.darkMode")}
    </DropdownMenuItem>
  );
};
ToggleTheme.displayName = "ToggleTheme";

export const ChangeCanvasBackground = () => {
  const { t } = useI18n();
  const appState = useUIAppState();
  const actionManager = useExcalidrawActionManager();
  const appProps = useAppProps();

  if (
    appState.viewModeEnabled ||
    !appProps.UIOptions.canvasActions.changeViewBackgroundColor
  ) {
    return null;
  }
  return (
    <div style={{ marginTop: "0.75rem" }}>
      <div
        data-testid="canvas-background-label"
        style={{
          fontSize: "0.875rem",
          marginBottom: "0.25rem",
          marginLeft: "0.5rem",
        }}
      >
        {t("labels.canvasBackground")}
      </div>
      <div style={{ padding: "0 0.625rem" }}>
        {actionManager.renderAction("changeViewBackgroundColor")}
      </div>
    </div>
  );
};
ChangeCanvasBackground.displayName = "ChangeCanvasBackground";

export const Export = () => {
  const { t } = useI18n();
  const setAppState = useExcalidrawSetAppState();
  return (
    <DropdownMenuItem
      icon={ExportIcon}
      onSelect={() => {
        setAppState({ openDialog: { name: "jsonExport" } });
      }}
      data-testid="json-export-button"
      aria-label={t("buttons.export")}
    >
      {t("buttons.export")}
    </DropdownMenuItem>
  );
};
Export.displayName = "Export";

export const LiveCollaborationTrigger = ({
  onSelect,
  isCollaborating,
}: {
  onSelect: () => void;
  isCollaborating: boolean;
}) => {
  const { t } = useI18n();
  return (
    <DropdownMenuItem
      data-testid="collab-button"
      icon={usersIcon}
      className={clsx({
        "active-collab": isCollaborating,
      })}
      onSelect={onSelect}
    >
      {t("labels.liveCollaboration")}
    </DropdownMenuItem>
  );
};

LiveCollaborationTrigger.displayName = "LiveCollaborationTrigger";

const PreferencesToggleToolLockItem = () => {
  const { t } = useI18n();
  const app = useApp();
  const appState = useUIAppState();

  return (
    <DropdownMenuItemCheckbox
      checked={appState.activeTool.locked}
      shortcut={getShortcutFromShortcutName("toolLock")}
      onSelect={(event) => {
        app.toggleLock();
        event.preventDefault();
      }}
    >
      {t("labels.preferences_toolLock")}
    </DropdownMenuItemCheckbox>
  );
};

const PreferencesBoxSelectionModeItem = () => {
  const { t } = useI18n();
  const appState = useUIAppState();
  const setAppState = useExcalidrawSetAppState();

  return (
    <DropdownMenuItemContentRadio<"contain" | "overlap">
      name="boxSelectionMode"
      icon={emptyIcon}
      value={appState.boxSelectionMode}
      onChange={(value) => {
        setAppState({
          boxSelectionMode: value,
        });
      }}
      choices={[
        {
          value: "contain",
          label: t("labels.boxSelectionContain"),
          ariaLabel: t("labels.boxSelectionContain"),
        },
        {
          value: "overlap",
          label: t("labels.boxSelectionOverlap"),
          ariaLabel: t("labels.boxSelectionOverlap"),
        },
      ]}
    >
      {t("labels.boxSelectionMode")}
    </DropdownMenuItemContentRadio>
  );
};

const PreferencesToggleSnapModeItem = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const appState = useUIAppState();
  return (
    <DropdownMenuItemCheckbox
      checked={appState.objectsSnapModeEnabled}
      shortcut={getShortcutFromShortcutName("objectsSnapMode")}
      onSelect={(event) => {
        actionManager.executeAction(actionToggleObjectsSnapMode);
        event.preventDefault();
      }}
    >
      {t("buttons.objectsSnapMode")}
    </DropdownMenuItemCheckbox>
  );
};

const PreferencesToggleArrowBindingItem = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const appState = useUIAppState();
  return (
    <DropdownMenuItemCheckbox
      checked={appState.bindingPreference === "enabled"}
      onSelect={(event) => {
        actionManager.executeAction(actionToggleArrowBinding);
        event.preventDefault();
      }}
    >
      {t("labels.arrowBinding")}
    </DropdownMenuItemCheckbox>
  );
};

const PreferencesToggleMidpointSnappingItem = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const appState = useUIAppState();
  return (
    <DropdownMenuItemCheckbox
      checked={appState.isMidpointSnappingEnabled}
      onSelect={(event) => {
        actionManager.executeAction(actionToggleMidpointSnapping);
        event.preventDefault();
      }}
    >
      {t("labels.midpointSnapping")}
    </DropdownMenuItemCheckbox>
  );
};

export const PreferencesToggleGridModeItem = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const appState = useUIAppState();

  return (
    <DropdownMenuItemCheckbox
      checked={appState.gridModeEnabled}
      shortcut={getShortcutFromShortcutName("gridMode")}
      onSelect={(event) => {
        actionManager.executeAction(actionToggleGridMode);
        event.preventDefault();
      }}
    >
      {t("labels.toggleGrid")}
    </DropdownMenuItemCheckbox>
  );
};

export const PreferencesToggleZenModeItem = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const appState = useUIAppState();
  return (
    <DropdownMenuItemCheckbox
      checked={appState.zenModeEnabled}
      shortcut={getShortcutFromShortcutName("zenMode")}
      onSelect={(event) => {
        actionManager.executeAction(actionToggleZenMode);
        event.preventDefault();
      }}
    >
      {t("buttons.zenMode")}
    </DropdownMenuItemCheckbox>
  );
};

const PreferencesToggleViewModeItem = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const appState = useUIAppState();
  if (!actionManager.isActionEnabled(actionToggleViewMode)) {
    return null;
  }
  return (
    <DropdownMenuItemCheckbox
      checked={appState.viewModeEnabled}
      shortcut={getShortcutFromShortcutName("viewMode")}
      onSelect={(event) => {
        actionManager.executeAction(actionToggleViewMode);
        event.preventDefault();
      }}
    >
      {t("labels.viewMode")}
    </DropdownMenuItemCheckbox>
  );
};

const PreferencesToggleElementPropertiesItem = () => {
  const { t } = useI18n();
  const actionManager = useExcalidrawActionManager();
  const appState = useUIAppState();
  return (
    <DropdownMenuItemCheckbox
      checked={appState.stats.open}
      shortcut={getShortcutFromShortcutName("stats")}
      onSelect={(event) => {
        actionManager.executeAction(actionToggleStats);
        event.preventDefault();
      }}
    >
      {t("stats.fullTitle")}
    </DropdownMenuItemCheckbox>
  );
};

export const Preferences = ({
  children,
  additionalItems,
}: {
  children?: React.ReactNode;
  additionalItems?: React.ReactNode;
}) => {
  const { t } = useI18n();
  return (
    <DropdownMenuSub>
      <DropdownMenuSub.Trigger icon={settingsIcon}>
        {t("labels.preferences")}
      </DropdownMenuSub.Trigger>
      <DropdownMenuSub.Content className="excalidraw-main-menu-preferences-submenu">
        {children || (
          <>
            <PreferencesBoxSelectionModeItem />
            <PreferencesToggleToolLockItem />
            <PreferencesToggleSnapModeItem />
            <PreferencesToggleGridModeItem />
            <PreferencesToggleZenModeItem />
            <PreferencesToggleViewModeItem />
            <PreferencesToggleElementPropertiesItem />
            <PreferencesToggleArrowBindingItem />
            <PreferencesToggleMidpointSnappingItem />
          </>
        )}
        {additionalItems}
      </DropdownMenuSub.Content>
    </DropdownMenuSub>
  );
};

Preferences.ToggleToolLock = PreferencesToggleToolLockItem;
Preferences.BoxSelectionMode = PreferencesBoxSelectionModeItem;
Preferences.ToggleSnapMode = PreferencesToggleSnapModeItem;
Preferences.ToggleArrowBinding = PreferencesToggleArrowBindingItem;
Preferences.ToggleMidpointSnapping = PreferencesToggleMidpointSnappingItem;
Preferences.ToggleGridMode = PreferencesToggleGridModeItem;
Preferences.ToggleZenMode = PreferencesToggleZenModeItem;
Preferences.ToggleViewMode = PreferencesToggleViewModeItem;
Preferences.ToggleElementProperties = PreferencesToggleElementPropertiesItem;

Preferences.displayName = "Preferences";

// packages/caliburn/src/components/main-menu/default-items.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  forwardRef,
  inject,
  input,
  output,
} from "@angular/core";

import { DEFAULT_CANVAS_BACKGROUND_PICKS, THEME } from "@excalidraw/common";

import { getShortcutFromShortcutName } from "@excalidraw/excalidraw/actions/shortcuts";
import { trackEvent } from "@excalidraw/excalidraw/analytics";
import { t } from "@excalidraw/excalidraw/i18n";

import type { Action } from "@excalidraw/excalidraw/actions/types";

import type { Theme } from "@excalidraw/element/types";

import {
  actionChangeViewBackgroundColor,
  actionClearCanvas,
  actionToggleTheme,
} from "../../actions/actionCanvas";
import {
  actionLoadScene,
  actionSaveToActiveFile,
} from "../../actions/actionExport";
import { actionShortcuts } from "../../actions/actionMenu";
import { actionToggleArrowBinding } from "../../actions/actionToggleArrowBinding";
import { actionToggleGridMode } from "../../actions/actionToggleGridMode";
import { actionToggleMidpointSnapping } from "../../actions/actionToggleMidpointSnapping";
import { actionToggleObjectsSnapMode } from "../../actions/actionToggleObjectsSnapMode";
import { actionToggleSearchMenu } from "../../actions/actionToggleSearchMenu";
import { actionToggleStats } from "../../actions/actionToggleStats";
import { actionToggleViewMode } from "../../actions/actionToggleViewMode";
import { actionToggleZenMode } from "../../actions/actionToggleZenMode";
import { CaliburnEditorComponent as CaliburnEditorComponentToken } from "../../editor.component";
import { CaliburnColorPickerComponent } from "../color-picker/color-picker.component";
import { CaliburnDropdownMenuItemContentRadioComponent } from "../dropdown-menu/dropdown-menu-item-content-radio.component";
import { CaliburnDropdownMenuItemLinkComponent } from "../dropdown-menu/dropdown-menu-item-link.component";
import { CaliburnDropdownMenuItemComponent } from "../dropdown-menu/dropdown-menu-item.component";
import {
  CaliburnDropdownMenuSubComponent,
  CaliburnDropdownMenuSubContentComponent,
  CaliburnDropdownMenuSubTriggerComponent,
} from "../dropdown-menu/dropdown-menu-sub.component";
import { openConfirmModal } from "../overwrite-confirm/overwrite-confirm-state";

import { translated } from "../../i18n";

import type { CaliburnEditorComponent } from "../../editor.component";
import type { RadioGroupChoice } from "../radio-group.component";

import type { Signal } from "@angular/core";

/**
 * Angular ports of upstream `main-menu/DefaultItems.tsx` — the composable
 * items a host (or `caliburn-default-main-menu`) drops into
 * `caliburn-main-menu`. Each renders exactly one upstream
 * `DropdownMenuItem`, keeping its classes, `data-testid`, shortcut and
 * aria-label; the wrapper custom element is `display: contents` (see
 * `styles.scss`) so the `<button>` stays a direct child of
 * `.dropdown-menu-container`.
 */
const injectEditor = () =>
  inject<CaliburnEditorComponent>(
    forwardRef(() => CaliburnEditorComponentToken),
  );

@Component({
  selector: "caliburn-menu-load-scene",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-load-scene.component.html",
})
export class CaliburnMenuLoadSceneComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("buttons.load"));
  protected readonly shortcut = getShortcutFromShortcutName("loadScene");

  protected enabled() {
    this.editor.changeGeneration();
    return this.editor.actionManager.isActionEnabled(actionLoadScene);
  }

  protected async handleSelect() {
    const elements = this.editor.scene.getNonDeletedElements();
    if (
      !elements.length ||
      (await openConfirmModal(this.editor, {
        title: t("overwriteConfirm.modal.loadFromFile.title"),
        actionLabel: t("overwriteConfirm.modal.loadFromFile.button"),
        color: "warning",
        descriptionKey: "overwriteConfirm.modal.loadFromFile.description",
      }))
    ) {
      this.editor.actionManager.executeAction(actionLoadScene, "ui");
    }
  }
}

@Component({
  selector: "caliburn-menu-save-to-active-file",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-save-to-active-file.component.html",
})
export class CaliburnMenuSaveToActiveFileComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("buttons.save"));
  protected readonly shortcut = getShortcutFromShortcutName("saveScene");

  protected enabled() {
    this.editor.changeGeneration();
    return this.editor.actionManager.isActionEnabled(actionSaveToActiveFile);
  }

  protected handleSelect() {
    this.editor.actionManager.executeAction(actionSaveToActiveFile, "ui");
  }
}

@Component({
  selector: "caliburn-menu-save-as-image",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-save-as-image.component.html",
})
export class CaliburnMenuSaveAsImageComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("buttons.exportImage"));
  protected readonly shortcut = getShortcutFromShortcutName("imageExport");

  protected handleSelect() {
    this.editor.batchCommits(() =>
      this.editor.setState({ openDialog: { name: "imageExport" } }),
    );
  }
}

/**
 * Upstream's library-level `DefaultMainMenu` composes every other item on this
 * page but not this one — excalidraw.com's own `AppMainMenu` adds it, right
 * before `SearchMenu`. Caliburn has no app-level menu, so
 * `caliburn-default-main-menu` takes that position for it; otherwise the
 * palette's menu trigger would have no call site at all.
 */
@Component({
  selector: "caliburn-menu-command-palette",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-command-palette.component.html",
})
export class CaliburnMenuCommandPaletteComponent {
  private readonly editor = injectEditor();

  readonly extraClass = input<string>("", { alias: "class" });

  protected readonly label = translated(() => t("commandPalette.title"));
  protected readonly shortcut = getShortcutFromShortcutName("commandPalette");

  protected handleSelect() {
    trackEvent("command_palette", "open", "menu");
    this.editor.batchCommits(() =>
      this.editor.setState({ openDialog: { name: "commandPalette" } }),
    );
  }
}

@Component({
  selector: "caliburn-menu-search",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-search.component.html",
})
export class CaliburnMenuSearchComponent {
  private readonly editor = injectEditor();

  readonly extraClass = input<string>("", { alias: "class" });

  protected readonly label = translated(() => t("search.title"));
  protected readonly shortcut = getShortcutFromShortcutName("searchMenu");

  protected handleSelect() {
    this.editor.actionManager.executeAction(actionToggleSearchMenu, "ui");
  }
}

@Component({
  selector: "caliburn-menu-help",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-help.component.html",
})
export class CaliburnMenuHelpComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("helpDialog.title"));

  protected handleSelect() {
    this.editor.actionManager.executeAction(actionShortcuts, "ui");
  }
}

@Component({
  selector: "caliburn-menu-clear-canvas",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-clear-canvas.component.html",
})
export class CaliburnMenuClearCanvasComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("buttons.clearReset"));

  protected enabled() {
    this.editor.changeGeneration();
    return this.editor.actionManager.isActionEnabled(actionClearCanvas);
  }

  protected handleSelect() {
    this.editor.activeConfirmDialog.set("clearCanvas");
  }
}

/**
 * Upstream's two branches: `allowSystemTheme` renders a light/dark/system
 * `DropdownMenuItemContentRadio` driven by `props.onThemeChange` (what the
 * app's menu uses), anything else the plain toggle item the built-in menu
 * uses. `theme` is the host's own theme setting, which may be `"system"`
 * while the editor's resolved `appState.theme` is light or dark.
 */
@Component({
  selector: "caliburn-menu-toggle-theme",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CaliburnDropdownMenuItemComponent,
    CaliburnDropdownMenuItemContentRadioComponent,
  ],
  templateUrl: "./menu-toggle-theme.component.html",
})
export class CaliburnMenuToggleThemeComponent {
  private readonly editor = injectEditor();

  readonly allowSystemTheme = input(false);
  readonly theme = input<Theme | "system">(THEME.LIGHT);

  protected readonly shortcut = getShortcutFromShortcutName("toggleTheme");
  protected readonly themeLabel = translated(() => t("labels.theme"));
  protected readonly isMobile = computed(
    () => this.editor.editorInterface.formFactor === "phone",
  );

  protected readonly themeChoices: Signal<
    RadioGroupChoice<Theme | "system">[]
  > = translated(() => [
    {
      value: THEME.LIGHT,
      icon: "sunIcon",
      ariaLabel: `${t("buttons.lightMode")} - ${this.shortcut}`,
    },
    {
      value: THEME.DARK,
      icon: "moonIcon",
      ariaLabel: `${t("buttons.darkMode")} - ${this.shortcut}`,
    },
    {
      value: "system",
      icon: "deviceDesktopIcon",
      ariaLabel: t("buttons.systemMode"),
    },
  ]);

  protected setTheme(theme: Theme | "system") {
    const onThemeChange = this.editor.props.onThemeChange;
    if (onThemeChange) {
      onThemeChange(theme);
      return;
    }
    console.warn(
      "MainMenu.DefaultItems.ToggleTheme: `<caliburn-editor/> onThemeChange` must be defined to use system theme selection.",
    );
  }

  protected isDark() {
    this.editor.changeGeneration();
    return this.editor.state.theme === THEME.DARK;
  }

  protected label() {
    return this.isDark() ? t("buttons.lightMode") : t("buttons.darkMode");
  }

  protected enabled() {
    this.editor.changeGeneration();
    return this.editor.actionManager.isActionEnabled(actionToggleTheme);
  }

  protected handleSelect(event: Event) {
    // do not close the menu when changing theme
    event.preventDefault();

    this.editor.actionManager.executeAction(actionToggleTheme, "ui");
  }
}

/**
 * Upstream delegates the picker to `actionManager.renderAction(
 * "changeViewBackgroundColor")`, whose `PanelComponent` is a `ColorPicker`
 * with `palette={null}` — top picks plus a hex input, no palette grid.
 */
@Component({
  selector: "caliburn-menu-change-canvas-background",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnColorPickerComponent],
  templateUrl: "./menu-change-canvas-background.component.html",
})
export class CaliburnMenuChangeCanvasBackgroundComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("labels.canvasBackground"));
  protected readonly canvasBackgroundPicks = DEFAULT_CANVAS_BACKGROUND_PICKS;

  protected visible() {
    this.editor.changeGeneration();
    return (
      !this.editor.state.viewModeEnabled &&
      !!this.editor.props.UIOptions.canvasActions.changeViewBackgroundColor
    );
  }

  protected currentColor() {
    this.editor.changeGeneration();
    return this.editor.state.viewBackgroundColor;
  }

  /** upstream's `updateData` for this action — also how the picker drives
   * `appState.openPopup` */
  protected readonly updateViewBackgroundColor = (formData?: any) => {
    this.editor.actionManager.executeAction(
      actionChangeViewBackgroundColor,
      "ui",
      formData,
    );
  };

  protected setColor(viewBackgroundColor: string) {
    this.updateViewBackgroundColor({ viewBackgroundColor });
  }
}

@Component({
  selector: "caliburn-menu-export",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-export.component.html",
})
export class CaliburnMenuExportComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("buttons.export"));

  protected handleSelect() {
    this.editor.batchCommits(() =>
      this.editor.setState({ openDialog: { name: "jsonExport" } }),
    );
  }
}

@Component({
  selector: "caliburn-menu-live-collaboration-trigger",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemComponent],
  templateUrl: "./menu-live-collaboration-trigger.component.html",
})
export class CaliburnMenuLiveCollaborationTriggerComponent {
  readonly isCollaborating = input(false);

  readonly select = output<void>();

  protected readonly label = translated(() => t("labels.liveCollaboration"));

  protected readonly itemClass = computed(() =>
    this.isCollaborating() ? "active-collab" : "",
  );
}

/**
 * Angular port of upstream `main-menu/DefaultItems.tsx`'s `Socials`. Upstream
 * renders three links to its own project (GitHub, X, Discord); caliburn has
 * no X or Discord presence, so those are dropped and the GitHub link points
 * at this app's own repository instead. Host-bound with `display: contents`
 * (see `styles.scss`) — upstream renders this as a fragment of sibling
 * `DropdownMenuItemLink`s, direct children of `.dropdown-menu-group`.
 */
@Component({
  selector: "caliburn-menu-socials",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CaliburnDropdownMenuItemLinkComponent],
  templateUrl: "./menu-socials.component.html",
})
export class CaliburnMenuSocialsComponent {}

type PreferencesToggle = {
  id: string;
  label: string;
  shortcut?: string;
  checked: boolean;
  toggle: () => void;
};

/**
 * Angular port of upstream `main-menu/DefaultItems.tsx`'s `Preferences` and
 * the nine `Preferences*Item`s it renders. Upstream also exports each row on
 * its own (`Preferences.ToggleGridMode`, …) so a host can pass its own
 * `children` in place of the default set; caliburn renders the default set
 * from one template and keeps only the `additionalItems` half of that API —
 * anything projected into this component is appended below the nine rows.
 *
 * `DropdownMenuItemCheckbox` is not a separate component here either: upstream's
 * is a one-line wrapper that hands `DropdownMenuItem` a `checkIcon`/`emptyIcon`
 * depending on `checked`, which is exactly what the template does inline.
 *
 * Persistence is upstream's: every field these rows write lives in `appState`,
 * and the host app persists it through `clearAppStateForLocalStorage`
 * (`appState.ts`'s `APP_STATE_STORAGE_CONF`, `browser: true`). `viewModeEnabled`
 * is `browser: false` there, so — as upstream — it is the one row that does not
 * survive a reload.
 */
@Component({
  selector: "caliburn-menu-preferences",
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CaliburnDropdownMenuItemComponent,
    CaliburnDropdownMenuItemContentRadioComponent,
    CaliburnDropdownMenuSubComponent,
    CaliburnDropdownMenuSubContentComponent,
    CaliburnDropdownMenuSubTriggerComponent,
  ],
  templateUrl: "./menu-preferences.component.html",
})
export class CaliburnMenuPreferencesComponent {
  private readonly editor = injectEditor();

  protected readonly label = translated(() => t("labels.preferences"));
  protected readonly boxSelectionLabel = translated(() =>
    t("labels.boxSelectionMode"),
  );
  protected readonly isMobile = computed(
    () => this.editor.editorInterface.formFactor === "phone",
  );

  protected readonly boxSelectionChoices: Signal<
    RadioGroupChoice<"contain" | "overlap">[]
  > = translated(() => [
    {
      value: "contain",
      label: t("labels.boxSelectionContain"),
      ariaLabel: t("labels.boxSelectionContain"),
    },
    {
      value: "overlap",
      label: t("labels.boxSelectionOverlap"),
      ariaLabel: t("labels.boxSelectionOverlap"),
    },
  ]);

  protected boxSelectionMode() {
    this.editor.changeGeneration();
    return this.editor.state.boxSelectionMode;
  }

  protected setBoxSelectionMode(boxSelectionMode: "contain" | "overlap") {
    this.editor.batchCommits(() => this.editor.setState({ boxSelectionMode }));
  }

  protected toggles(): PreferencesToggle[] {
    this.editor.changeGeneration();
    const state = this.editor.state;
    const rows: PreferencesToggle[] = [
      {
        id: "tool-lock",
        label: t("labels.preferences_toolLock"),
        shortcut: getShortcutFromShortcutName("toolLock"),
        checked: state.activeTool.locked,
        toggle: () => this.editor.toggleToolLock(),
      },
      {
        id: "objects-snap-mode",
        label: t("buttons.objectsSnapMode"),
        shortcut: getShortcutFromShortcutName("objectsSnapMode"),
        checked: state.objectsSnapModeEnabled,
        toggle: () => this.execute(actionToggleObjectsSnapMode),
      },
      {
        id: "grid-mode",
        label: t("labels.toggleGrid"),
        shortcut: getShortcutFromShortcutName("gridMode"),
        checked: state.gridModeEnabled,
        toggle: () => this.execute(actionToggleGridMode),
      },
      {
        id: "zen-mode",
        label: t("buttons.zenMode"),
        shortcut: getShortcutFromShortcutName("zenMode"),
        checked: state.zenModeEnabled,
        toggle: () => this.execute(actionToggleZenMode),
      },
    ];

    if (this.editor.actionManager.isActionEnabled(actionToggleViewMode)) {
      rows.push({
        id: "view-mode",
        label: t("labels.viewMode"),
        shortcut: getShortcutFromShortcutName("viewMode"),
        checked: state.viewModeEnabled,
        toggle: () => this.execute(actionToggleViewMode),
      });
    }

    rows.push(
      {
        id: "element-properties",
        label: t("stats.fullTitle"),
        shortcut: getShortcutFromShortcutName("stats"),
        checked: state.stats.open,
        toggle: () => this.execute(actionToggleStats),
      },
      {
        id: "arrow-binding",
        label: t("labels.arrowBinding"),
        checked: state.bindingPreference === "enabled",
        toggle: () => this.execute(actionToggleArrowBinding),
      },
      {
        id: "midpoint-snapping",
        label: t("labels.midpointSnapping"),
        checked: state.isMidpointSnappingEnabled,
        toggle: () => this.execute(actionToggleMidpointSnapping),
      },
    );

    return rows;
  }

  /** upstream's rows all `preventDefault()` so the menu stays open while a
   * preference is being flipped (see `dropdown-menu-item.component.ts`) */
  protected onToggle(row: PreferencesToggle, event: Event) {
    event.preventDefault();
    row.toggle();
  }

  private execute(action: Action) {
    this.editor.actionManager.executeAction(action, "ui");
  }
}
